Get-ScheduledTask -TaskName ServerManager | Disable-ScheduledTask -Verbose
C:\ProgramData\chocolatey\choco upgrade brave -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade firefox -y --limitoutput --params "ALLUSERS=1"
C:\ProgramData\chocolatey\choco upgrade 7zip -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade Putty -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade filezilla -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade curl -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade winscp -y --limitoutput --params "ALLUSERS=1"
C:\ProgramData\chocolatey\choco upgrade azure-cli -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade azcopy -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade microsoftazurestorageexplorer -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade postman -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade terraform -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade vscode -y --limitoutput --params "ALLUSERS=1"
#C:\ProgramData\chocolatey\choco upgrade git -y --limitoutput --params "ALLUSERS=1"
